export const productKeywords = [
  "ZOE STORE",
  "moda feminina",
  "roupa feminina",
  "comprar online",
  "e-commerce moda",
  "loja de roupa feminina",
  "produto",
  "detalhes do produto",
  "descrição do produto",
  "imagem do produto",
  "preço",
  "adicionar ao carrinho",
  // "tamanhos",
  // "cores",
  "disponibilidade",
  "avaliações do produto",
  // "frete",
  // "entrega",
  // "devolução",
  // "garantia",
  "material",
  "composição",
  // "cuidado com a roupa",
  "promoção",
  "oferta",
  "novidade",
  "lançamento",
  "item em destaque",
  "tendência",
  "coleção",
];
