export const keywords = [
  "ZOE STORE",
  "moda feminina",
  "roupa feminina",
  "coleção exclusiva",
  "elegância",
  "mulher moderna",
  "look perfeito",
  "roupas para todas ocasiões",
  "enviar para Brasil",
  "comprar online",
  "e-commerce moda",
  "vestidos",
  "blusas",
  "saias",
  "calças",
  "acessórios de moda",
  "tendências de moda",
  "fashion",
  "estilo feminino",
  "novidades moda",
  "loja de roupa feminina",
  "modafeminina online",
  "envio seguro",
  "frete para todo Brasil",
  "qualidade",
  "roupas elegantes",
  "coleção de verão",
  "coleção de inverno",
  "promoções de moda",
  "roupas baratas",
  "descontos",
  "roupas da moda",
  "tendência",
  "conforto",
  "versatilidade",
  "roupas de festa",
  "casual",
  "trabalho",
  "eventos",
  "roupa de marca",
  "boutique online",
  "multistore",
  "peças únicas",
  "feminino",
  "feminina",
];
